### ISSUE TITLE
Shutdown not working

### ISSUE THREAD

**Issue by Aergernis** [ArjenR/x120x_upsd#8]
Hi,

when running the daemon or the script directly i get the following Error:

I thinks it's because i don't have a Temperature Sensor installed.

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/bin/x120x_upsd.py", line 339, in _selfprotect
    if temp >= self._MAXIMAL_CHARGE_TEMPERATURE and self._fan.state != 'on':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

It's reporting Battery stats but the rest dosen't semm to work. It's not shutting down by time, % or Voltage. Also `seconds_to_shutdown` is always 0.

when i set temp variable (line 328) to a fixed value it's working.

What I've also noticed is that shutdown is also not working with the exact same behavior when the battery is above the set loading valve.  ( not yet 100% sure, I'll test it the next days)

**Comment by ArjenR** [comment]
Hi I was away so could not get back to you. Found the issue with not having a temp sensor. Fixed in my local branch and will get that on github later.

Not shutting down when the battery is above set max capacity is by design. It will shutdown when there is no power and the battery is at/below max set capacity. If so configured of course.

**Comment by Aergernis** [comment]
> Hi I was away so could not get back to you. Found the issue with not having a temp sensor. Fixed in my local branch and will get that on github later.
> 
> Not shutting down when the battery is above set max capacity is by design. It will shutdown when there is no power and the battery is at/below max set capacity. If so configured of course.

Thanks again.

I've tested it it again, and it's working. Maybe i've tested it before i set the Temperature to a fixed value and the "No Temperature Sensor Bug" was still present.

**Comment by ArjenR** [comment]
Fix for not having temp sensor
